name: Deploy Blazor WebAssembly

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Debug Step: List files in the repository
    - name: List files for debugging
      run: ls -R

    # Step 2: Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore MazeGameBlazorApp/MazeGameBlazor/MazeGameBlazor/MazeGameBlazor.csproj

    # Step 4: Build the Blazor WebAssembly app
    - name: Build Blazor WebAssembly
      run: dotnet publish MazeGameBlazorApp/MazeGameBlazor/MazeGameBlazor/MazeGameBlazor.csproj -c Release -o build

    # Step 5: Deploy via FTP to your server
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/wwwroot/
        server-dir: /var/www/maze.aedev.pro/
        protocol: ftps
