name: Deploy Blazor WebAssembly

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'  

    # Step 3: Build the Blazor WebAssembly app
    - name: Build Blazor WebAssembly
      run: dotnet publish MazeGameBlazorApp/MazeGameBlazorApp.csproj -c Release -o build

    # Step 4: Deploy via FTP to your server
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/wwwroot/
        server-dir: /var/www/maze.aedev.pro/
        protocol: ftps 
