name: Build and Deploy Blazor WebAssembly

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Debug Step: List files in the repository
    - name: List files for debugging
      run: ls -R

    # Step 2: Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore MazeGameBlazorApp/MazeGameBlazor/MazeGameBlazor/MazeGameBlazor.csproj

    # Step 4: Build the Blazor WebAssembly app
    - name: Build Blazor WebAssembly
      run: dotnet publish MazeGameBlazorApp/MazeGameBlazor/MazeGameBlazor/MazeGameBlazor.csproj -c Release -o build

    # Step 5: Deploy Built Files to the Production Server
    - name: Deploy Built Files to Server
      run: |
        # Configure SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H aedev.pro >> ~/.ssh/known_hosts

        # Clone the repository and deploy the build files
        git clone ssh://a3emond@aedev.pro:/var/www/maze.aedev.pro deploy_repo
        cd deploy_repo
        rm -rf *
        cp -r ../build/* .
        git add .
        git commit -m "Deploy new build from GitHub Actions" || echo "No changes to commit"
        git push origin master
      env:
        GIT_SSH_COMMAND: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no
